apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: __APP_NAME__
  description: __APP_NAME__ service
  tags:
    - kubernetes
    - gitops
spec:
  type: service
  lifecycle: production
  owner: platform
