apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: __APP_NAME__
  labels:
    app: __APP_NAME__
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: __APP_NAME__-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: apps/__APP_NAME__
