apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: react-frontend-template
  title: React Frontend App
  description: Create a new React frontend service using the homelab platform template
spec:
  owner: user:guest
  type: website

  parameters:
    - title: App information
      required:
        - app_name
      properties:
        app_name:
          title: App Name
          type: string
          description: Name of the app to generate

  steps:
    - id: log
      name: Log app name
      action: debug:log
      input:
        message: Creating ${{ parameters.app_name }}

  output:
    text:
      - title: Next step
        content: Run the homelab-platform generator locally for now.
