apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${{ values.appName }}-staging

resources:
- ../../base
- configmap.yaml
{%- if values.ingress %}
- ingress.yaml
{%- endif %}

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: ${{ values.appName }}

images:
- name: ${{ values.appName }}
  newName: ${{ values.image }}
  newTag: latest

labels:
- pairs:
    environment: staging
